// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ShowInfo {
    /**
     * Creates a new ShowInfo instance.
     * @param {Partial<ShowInfo>} [$$source = {}] - The source object to create the ShowInfo.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * 标题
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * 内容体
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("footer" in $$source)) {
            /**
             * Footer
             * @member
             * @type {string}
             */
            this["footer"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShowInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShowInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShowInfo(/** @type {Partial<ShowInfo>} */($$parsedSource));
    }
}
