// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Alert    提示
 * title    标题
 * body     body体
 * destroy  关闭时间 0代表不会关闭
 * @param {string} title
 * @param {string} body
 * @param {number} destroy
 * @returns {$CancellablePromise<void>}
 */
export function Alert(title, body, destroy) {
    return $Call.ByID(4073326155, title, body, destroy);
}

/**
 * @param {$models.ShowInfo} str
 * @returns {$CancellablePromise<void>}
 */
export function Confirm(str) {
    return $Call.ByID(1626782001, str);
}

/**
 * @param {string} str
 * @returns {$CancellablePromise<void>}
 */
export function Show(str) {
    return $Call.ByID(794715274, str);
}
