// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class NewWindowOptions {
    /**
     * Creates a new NewWindowOptions instance.
     * @param {Partial<NewWindowOptions>} [$$source = {}] - The source object to create the NewWindowOptions.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * 窗口名称
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("width" in $$source)) {
            /**
             * 宽度
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * 高度
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * 标题
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("place" in $$source)) {
            /**
             * 位置 center、bottomLeft、bottomRight、topRight、topLeft
             * @member
             * @type {string}
             */
            this["place"] = "";
        }
        if (!("frameLess" in $$source)) {
            /**
             * 无边框
             * @member
             * @type {boolean}
             */
            this["frameLess"] = false;
        }
        if (!("url" in $$source)) {
            /**
             * 打开地址
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("isFullscreen" in $$source)) {
            /**
             * 是否全屏
             * @member
             * @type {boolean}
             */
            this["isFullscreen"] = false;
        }
        if (!("alwaysOnTop" in $$source)) {
            /**
             * 是否在顶层
             * @member
             * @type {boolean}
             */
            this["alwaysOnTop"] = false;
        }
        if (!("hiddenOnTaskbar" in $$source)) {
            /**
             * 在任务栏隐藏图标
             * @member
             * @type {boolean}
             */
            this["hiddenOnTaskbar"] = false;
        }
        if (!("disableResize" in $$source)) {
            /**
             * 是否禁止缩放
             * @member
             * @type {boolean}
             */
            this["disableResize"] = false;
        }
        if (!("f5Reload" in $$source)) {
            /**
             * f5键刷新
             * @member
             * @type {boolean}
             */
            this["f5Reload"] = false;
        }
        if (!("f12DevTools" in $$source)) {
            /**
             * f12DevTools
             * @member
             * @type {boolean}
             */
            this["f12DevTools"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NewWindowOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NewWindowOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NewWindowOptions(/** @type {Partial<NewWindowOptions>} */($$parsedSource));
    }
}
